server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost/test?characterEncoding=utf8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: provider-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instace_id:${server.port}}
